### ISSUE TITLE
missing smalltalk.css in local client?

### ISSUE THREAD

**Issue by mrueger42** [guillermoamaral/Webside#6]
./src/components/parts/CodeEditor.js
Module not found: Can't resolve 'codemirror/theme/smalltalk.css' in '/Users/michael/Development/projects/labware/projects/webside/Webside/client/src/components/parts'

also in CodeMerge.js

if I comment out the references the client launches

**Comment by guillermoamaral** [comment]
Hi there!

I'll check it and make it work.

Thanks for your feedback!

Guille
________________________________

Guillermo Amaral
Development Manager

t: +1 281 254 7600
m: +54 9 11 63 03 76 82
e: guillermo.amaral@aucerna.com
Learn more about Aucerna's ranking here
Confidentiality Notice:
 The information transmitted herein may contain confidential, proprietary and/or privileged material which belongs to Aucerna and is only for the intended addressee(s). Any unauthorized review, distribution or other use of this information is prohibited. Finally, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email. If you received this email in error, please contact us at (403) 270-3270 or by return email and delete this email and any copies immediately.  v&7.11.1989&$

**Comment by guillermoamaral** [comment]
Now CodeEditor and CodeMerge components use customized versions of tokenizer and style sheet (named SmalltalkMode.js and SmalltalkMode.css respectively)
